#! /bin/bash

nohup /home/lachlan/ArkServer/ShooterGame/Binaries/Linux/RgServer Ragnarok?AltSaveDirectoryName=RagnarokSaves?RCONEnabled=True?RCONPort=27024?ServerAdminPassword=Winslow1?QueryPort=27019?Port=7781?SessionName=Ragrrrrok? -server -log -NoTransferFromFiltering -clusterid=universe1 -ClusterDirOverride=/home/lachlan/ArkServer/ShooterGame/ClusterData &
